Update sultan.yml

diff --git a/.github/workflows/sultan.yml b/.github/workflows/sultan.yml
--- a/.github/workflows/sultan.yml
+++ b/.github/workflows/sultan.yml
@@ -95,19 +95,28 @@ jobs:
 
           echo "Applying wild SUSFS Fix patches..."
           cp ../../kernel_patches/wild/susfs_fix_patches/v1.5.9/fix_core_hook.c.patch ./
-          patch -p1 --forward < fix_core_hook.c.patch
+          patch -p1 --forward < fix_core_hook.c.patch || true
 
           cp ../../kernel_patches/wild/susfs_fix_patches/v1.5.9/fix_sucompat.c.patch ./
-          patch -p1 --forward < fix_sucompat.c.patch
+          patch -p1 --forward < fix_sucompat.c.patch  || true
 
           cp ../../kernel_patches/wild/susfs_fix_patches/v1.5.9/fix_kernel_compat.c.patch ./
-          patch -p1 --forward < fix_kernel_compat.c.patch
+          patch -p1 --forward < fix_kernel_compat.c.patch || true
           
           # Change to common directory and apply SUSFS patch
           cd ..
           patch -p1 < 50_add_susfs_in_gki-${{ inputs.android_version }}-${{ inputs.kernel_version }}.patch || true
           cp ../kernel_patches/sultan/sys.c_fix.patch ./
-          patch -p1 --fuzz=3 < sys.c_fix.patch
+          patch -p1 --fuzz=3 < sys.c_fix.patch || true
+
+      - name: Upload Patch Reject Files
+        if: failure()  # Only run if previous steps failed
+        uses: actions/upload-artifact@v4
+        with:
+         name: patch-rejects-${{ inputs.codename }}
+         path: |
+           **/*.rej
+         retention-days: 5  # Keep artifacts for 5 days
 
       - name: Apply KSU Hooks
         run: |
