Update sultan.yml

diff --git a/.github/workflows/sultan.yml b/.github/workflows/sultan.yml
--- a/.github/workflows/sultan.yml
+++ b/.github/workflows/sultan.yml
@@ -97,10 +97,17 @@ jobs:
           patch -p1 -F 3 < 50_add_susfs_in_gki-${{ inputs.android_version }}-${{ inputs.kernel_version }}.patch || true
           patch -p1 < 60_scope-minimized_manual_hooks.patch
 
-          # Applying KSU managers patch
-          curl -Ls https://raw.githubusercontent.com/infectedmushi/kernel_patches/refs/heads/main/next/0001-add-more-managers.patch | patch -p1
-        
-    
+          echo "Applying KSU managers patch..."
+          curl -Ls https://raw.githubusercontent.com/infectedmushi/kernel_patches/refs/heads/main/next/0001-add-more-managers.patch -o 0001-add-more-managers.patch
+          if [ ! -f 0001-add-more-managers.patch ]; then
+          echo "Error: Failed to download KSU managers patch"
+          exit 1
+          fi
+          if [ ! -f kernel/apk_sign.c ]; then
+           echo "Error: kernel/apk_sign.c not found for patching"
+          exit 1
+          fi
+          patch -p1 < 0001-add-more-managers.patch
 
     
 
